### ISSUE TITLE
Usage question: zipping datasets

### ISSUE THREAD

**Issue by lnlyssg** [ZOSOpenTools/zipport#12]
I was hoping that I could use this port to zip a mainframe dataset using the "//'USERID.DATA'" method as used with [cp](https://www.ibm.com/docs/en/zos/2.4.0?topic=descriptions-cp-copy-file#d97484e1875) but this results in a `zip warning: name not matched:` error. I can copy the dataset into USS and then zip but this requires additional steps. Is there any way round this?

**Comment by IgorTodorovskiIBM** [comment]
> I was hoping that I could use this port to zip a mainframe dataset using the "//'USERID.DATA'" method as used with [cp](https://www.ibm.com/docs/en/zos/2.4.0?topic=descriptions-cp-copy-file#d97484e1875) but this results in a `zip warning: name not matched:` error. I can copy the dataset into USS and then zip but this requires additional steps. Is there any way round this?

Zip uses C open() which does not support dataset I/O. Do you have dsfs set up on your system? That is the future direction for dataset I/O on z/OS UNIX - https://www.ibm.com/docs/en/zos/2.5.0?topic=guide-overview-zos-data-set-file-system

**Comment by lnlyssg** [comment]
Unfortunately this is a 2.4 system so seems I'm out of luck for now
